services:
  db:
    image: postgres
    restart: always
    ports:
      - "5438:5432"
    environment:
      POSTGRES_PASSWORD: pass123
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - "C:/Users/frj/Documents/Training/Nestjs/auth-extension/docker/postgres-data:/var/lib/postgresql/data"
  redis:
    image: redis
    ports:
      - "6379:6379"
    restart: always
  pghero:
    image: ankane/pghero
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      PGHERO_USERNAME: admin
      PGHERO_PASSWORD: secret
    volumes:
      - "./pghero.yml:/app/config/pghero.yml:ro"
    restart: always

#   Start docker-compose
#  NOTE: docker-compose down (to take it down)

# docker-compose up -d